# Generated by Django 4.2.15 on 2024-09-10 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('home_spread', models.CharField(max_length=6)),
                ('ou', models.CharField(max_length=6)),
                ('date', models.DateField(verbose_name='date of game')),
                ('home_final', models.IntegerField(default=0)),
                ('away_final', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over', models.CharField(max_length=50)),
                ('under', models.CharField(max_length=50)),
                ('fav', models.CharField(max_length=50)),
                ('dog', models.CharField(max_length=50)),
                ('week', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
