# Generated by Django 4.2.15 on 2024-09-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolapp', '0002_remove_game_date_game_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_week', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
