# Generated by Django 4.2.15 on 2024-09-13 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poolapp', '0003_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_wins', models.IntegerField(default=0)),
                ('overall_loss', models.IntegerField(default=0)),
                ('over_win', models.IntegerField(default=0)),
                ('over_loss', models.IntegerField(default=0)),
                ('under_win', models.IntegerField(default=0)),
                ('under_loss', models.IntegerField(default=0)),
                ('fav_loss', models.IntegerField(default=0)),
                ('fav_win', models.IntegerField(default=0)),
                ('dog_loss', models.IntegerField(default=0)),
                ('dog_win', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
