# Generated by Django 4.2.15 on 2024-09-13 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolapp', '0004_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'permissions': [('can_update', 'Users can update games')]},
        ),
    ]
