# Generated by Django 4.2.15 on 2024-09-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolapp', '0005_alter_game_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dog_push',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='fav_push',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='over_push',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='overall_push',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='under_push',
            field=models.IntegerField(default=0),
        ),
    ]
